In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# List only files in the current directory
files = [f for f in os.listdir('.') if os.path.isfile(f)]

for f in files:
    print(f)
    
txt_files = [f for f in files if f.lower().endswith('.txt')]

print(txt_files)

Cambridge IV 2024 (22 rooms).txt
Eristic BPD (25 rms).txt
Hart House Intervasity 2024 (25rms).txt
Kampala open 3.0 (25 rms).txt
Kumasi Debate Open 2024 (21 rms).txt
Macau Debate Open 2025(23 rms).txt
Malaysia Online Debate Open 2025（25 rms）.txt
Osaka IV 2024 (21 rms).txt
Oxford IV 2024 (28 rms).txt
Princeton IV 2024 (32 rms).txt
Scrape_tab_to_txt.ipynb
Shanghai International Debate Open 2025(38 rms).txt
Shri Ram Pre ABP (20 rms).txt
St Andrew's Pre-EUDC 2025.txt
St Andrews Pre-EUDC Competition (20 rms).txt
Tab2Database.ipynb
Tab2Database2.ipynb
The Delhi Debate 2024 (21 rms).txt
Tournament_masterlist.xlsx
Uhuru Worlds 2025 (83 rms).txt
Vienna IV 2025 (22rms).txt
Vienna Online Open Pre-EUDC 2024 (27 rms).txt
Vienna Online Open Pre-WUDC 2024 (32rms).txt
Warwick Pre-EUDC 2025 (29 rms).txt
Warwick Pre-EUDC 2025 (29 rms)_rounds_done.xlsx
Warwick Pre-EUDC 2025 (29 rms)_speakertab_done.xlsx
Warwick Pre-EUDC 2025 (29 rms)_teamtab_done.xlsx
['Cambridge IV 2024 (22 rooms).txt', 'Eristic BPD (25 rms).txt', 'Hart House Intervasity 2024 (25rms).txt', 'Kampala open 3.0 (25 rms).txt', 'Kumasi Debate Open 2024 (21 rms).txt', 'Macau Debate Open 2025(23 rms).txt', 'Malaysia Online Debate Open 2025（25 rms）.txt', 'Osaka IV 2024 (21 rms).txt', 'Oxford IV 2024 (28 rms).txt', 'Princeton IV 2024 (32 rms).txt', 'Shanghai International Debate Open 2025(38 rms).txt', 'Shri Ram Pre ABP (20 rms).txt', "St Andrew's Pre-EUDC 2025.txt", 'St Andrews Pre-EUDC Competition (20 rms).txt', 'The Delhi Debate 2024 (21 rms).txt', 'Uhuru Worlds 2025 (83 rms).txt', 'Vienna IV 2025 (22rms).txt', 'Vienna Online Open Pre-EUDC 2024 (27 rms).txt', 'Vienna Online Open Pre-WUDC 2024 (32rms).txt', 'Warwick Pre-EUDC 2025 (29 rms).txt']

In [5]:
def get_comp_name(txt_file):
    comp_name = txt_file[:-4]
    print(comp_name)
    df = pd.read_csv(txt_file, delimiter ='\t', on_bad_lines='warn')
    print(len(df))
    return df, comp_name

for i in range(len(txt_files)):
    df, comp_name = get_comp_name(txt_files[i])
df

Cambridge IV 2024 (22 rooms)
725
Eristic BPD (25 rms)
850
Hart House Intervasity 2024 (25rms)
856
Kampala open 3.0 (25 rms)
1259
Kumasi Debate Open 2024 (21 rms)
746
Macau Debate Open 2025(23 rms)
788
Malaysia Online Debate Open 2025（25 rms）
771
Osaka IV 2024 (21 rms)
1027
Oxford IV 2024 (28 rms)
946
Princeton IV 2024 (32 rms)
1137
Shanghai International Debate Open 2025(38 rms)
1488
Shri Ram Pre ABP (20 rms)
654
St Andrew's Pre-EUDC 2025
775
St Andrews Pre-EUDC Competition (20 rms)
688
The Delhi Debate 2024 (21 rms)
723
Uhuru Worlds 2025 (83 rms)
3401
Vienna IV 2025 (22rms)
764
Vienna Online Open Pre-EUDC 2024 (27 rms)

Skipping line 174: expected 14 fields, saw 15
Skipping line 176: expected 14 fields, saw 15
Skipping line 178: expected 14 fields, saw 15
Skipping line 180: expected 14 fields, saw 15
Skipping line 182: expected 14 fields, saw 15
Skipping line 184: expected 14 fields, saw 15
Skipping line 186: expected 14 fields, saw 15
Skipping line 188: expected 14 fields, saw 15
Skipping line 190: expected 14 fields, saw 15
Skipping line 192: expected 14 fields, saw 15
Skipping line 194: expected 14 fields, saw 15
Skipping line 196: expected 14 fields, saw 15
Skipping line 198: expected 14 fields, saw 15
Skipping line 200: expected 14 fields, saw 15
Skipping line 202: expected 14 fields, saw 15
Skipping line 204: expected 14 fields, saw 15
Skipping line 206: expected 14 fields, saw 15
Skipping line 208: expected 14 fields, saw 15
Skipping line 210: expected 14 fields, saw 15
Skipping line 212: expected 14 fields, saw 15
Skipping line 214: expected 14 fields, saw 15
Skipping line 216: expected 14 fields, saw 15
Skipping line 218: expected 14 fields, saw 15
Skipping line 220: expected 14 fields, saw 15
Skipping line 222: expected 14 fields, saw 15
Skipping line 224: expected 14 fields, saw 15
Skipping line 226: expected 14 fields, saw 15
Skipping line 228: expected 14 fields, saw 15
Skipping line 230: expected 14 fields, saw 15
Skipping line 232: expected 14 fields, saw 15
Skipping line 234: expected 14 fields, saw 15
Skipping line 236: expected 14 fields, saw 15
Skipping line 238: expected 14 fields, saw 15
Skipping line 240: expected 14 fields, saw 15
Skipping line 242: expected 14 fields, saw 15
Skipping line 244: expected 14 fields, saw 15
Skipping line 246: expected 14 fields, saw 15
Skipping line 248: expected 14 fields, saw 15
Skipping line 250: expected 14 fields, saw 15
Skipping line 252: expected 14 fields, saw 15
Skipping line 254: expected 14 fields, saw 15
Skipping line 256: expected 14 fields, saw 15
Skipping line 258: expected 14 fields, saw 15
Skipping line 260: expected 14 fields, saw 15
Skipping line 262: expected 14 fields, saw 15
Skipping line 264: expected 14 fields, saw 15
Skipping line 266: expected 14 fields, saw 15
Skipping line 268: expected 14 fields, saw 15
Skipping line 270: expected 14 fields, saw 15
Skipping line 272: expected 14 fields, saw 15
Skipping line 274: expected 14 fields, saw 15
Skipping line 276: expected 14 fields, saw 15
Skipping line 278: expected 14 fields, saw 15
Skipping line 280: expected 14 fields, saw 15
Skipping line 282: expected 14 fields, saw 15
Skipping line 284: expected 14 fields, saw 15
Skipping line 286: expected 14 fields, saw 15
Skipping line 288: expected 14 fields, saw 15
Skipping line 290: expected 14 fields, saw 15
Skipping line 292: expected 14 fields, saw 15
Skipping line 294: expected 14 fields, saw 15
Skipping line 296: expected 14 fields, saw 15
Skipping line 298: expected 14 fields, saw 15
Skipping line 300: expected 14 fields, saw 15
Skipping line 302: expected 14 fields, saw 15
Skipping line 304: expected 14 fields, saw 15
Skipping line 306: expected 14 fields, saw 15
Skipping line 308: expected 14 fields, saw 15
Skipping line 310: expected 14 fields, saw 15
Skipping line 312: expected 14 fields, saw 15
Skipping line 314: expected 14 fields, saw 15
Skipping line 316: expected 14 fields, saw 15
Skipping line 318: expected 14 fields, saw 15
Skipping line 320: expected 14 fields, saw 15
Skipping line 322: expected 14 fields, saw 15
Skipping line 324: expected 14 fields, saw 15
Skipping line 326: expected 14 fields, saw 15
Skipping line 328: expected 14 fields, saw 15
Skipping line 330: expected 14 fields, saw 15
Skipping line 332: expected 14 fields, saw 15
Skipping line 334: expected 14 fields, saw 15
Skipping line 336: expected 14 fields, saw 15
Skipping line 338: expected 14 fields, saw 15
Skipping line 340: expected 14 fields, saw 15
Skipping line 342: expected 14 fields, saw 15
Skipping line 344: expected 14 fields, saw 15
Skipping line 346: expected 14 fields, saw 15
Skipping line 348: expected 14 fields, saw 15
Skipping line 350: expected 14 fields, saw 15
Skipping line 352: expected 14 fields, saw 15
Skipping line 354: expected 14 fields, saw 15
Skipping line 356: expected 14 fields, saw 15
Skipping line 358: expected 14 fields, saw 15
Skipping line 360: expected 14 fields, saw 15
Skipping line 362: expected 14 fields, saw 15
Skipping line 364: expected 14 fields, saw 15
Skipping line 366: expected 14 fields, saw 15
Skipping line 368: expected 14 fields, saw 15
Skipping line 370: expected 14 fields, saw 15
Skipping line 372: expected 14 fields, saw 15
Skipping line 374: expected 14 fields, saw 15
Skipping line 376: expected 14 fields, saw 15
Skipping line 378: expected 14 fields, saw 15
Skipping line 380: expected 14 fields, saw 15
Skipping line 382: expected 14 fields, saw 15
Skipping line 384: expected 14 fields, saw 15
Skipping line 386: expected 14 fields, saw 15
Skipping line 388: expected 14 fields, saw 15
Skipping line 390: expected 14 fields, saw 15
Skipping line 392: expected 14 fields, saw 15
Skipping line 394: expected 14 fields, saw 15
Skipping line 396: expected 14 fields, saw 15
Skipping line 398: expected 14 fields, saw 15
Skipping line 400: expected 14 fields, saw 15
Skipping line 402: expected 14 fields, saw 15
Skipping line 404: expected 14 fields, saw 15
Skipping line 406: expected 14 fields, saw 15
Skipping line 408: expected 14 fields, saw 15
Skipping line 410: expected 14 fields, saw 15
Skipping line 412: expected 14 fields, saw 15
Skipping line 414: expected 14 fields, saw 15
Skipping line 416: expected 14 fields, saw 15
Skipping line 418: expected 14 fields, saw 15
Skipping line 420: expected 14 fields, saw 15
Skipping line 422: expected 14 fields, saw 15
Skipping line 424: expected 14 fields, saw 15
Skipping line 426: expected 14 fields, saw 15
Skipping line 428: expected 14 fields, saw 15
Skipping line 430: expected 14 fields, saw 15
Skipping line 432: expected 14 fields, saw 15
Skipping line 434: expected 14 fields, saw 15
Skipping line 436: expected 14 fields, saw 15
Skipping line 438: expected 14 fields, saw 15
Skipping line 440: expected 14 fields, saw 15
Skipping line 442: expected 14 fields, saw 15
Skipping line 444: expected 14 fields, saw 15
Skipping line 446: expected 14 fields, saw 15
Skipping line 448: expected 14 fields, saw 15
Skipping line 450: expected 14 fields, saw 15
Skipping line 452: expected 14 fields, saw 15
Skipping line 454: expected 14 fields, saw 15
Skipping line 456: expected 14 fields, saw 15
Skipping line 458: expected 14 fields, saw 15
Skipping line 460: expected 14 fields, saw 15
Skipping line 462: expected 14 fields, saw 15
Skipping line 464: expected 14 fields, saw 15
Skipping line 466: expected 14 fields, saw 15
Skipping line 468: expected 14 fields, saw 15
Skipping line 470: expected 14 fields, saw 15
Skipping line 472: expected 14 fields, saw 15
Skipping line 474: expected 14 fields, saw 15
Skipping line 476: expected 14 fields, saw 15
Skipping line 478: expected 14 fields, saw 15
Skipping line 480: expected 14 fields, saw 15
Skipping line 482: expected 14 fields, saw 15
Skipping line 484: expected 14 fields, saw 15
Skipping line 486: expected 14 fields, saw 15
Skipping line 488: expected 14 fields, saw 15
Skipping line 490: expected 14 fields, saw 15
Skipping line 492: expected 14 fields, saw 15
Skipping line 494: expected 14 fields, saw 15
Skipping line 496: expected 14 fields, saw 15
Skipping line 498: expected 14 fields, saw 15
Skipping line 500: expected 14 fields, saw 15
Skipping line 502: expected 14 fields, saw 15
Skipping line 504: expected 14 fields, saw 15
Skipping line 506: expected 14 fields, saw 15
Skipping line 508: expected 14 fields, saw 15
Skipping line 510: expected 14 fields, saw 15

940
Vienna Online Open Pre-WUDC 2024 (32rms)
1096
Warwick Pre-EUDC 2025 (29 rms)
1015

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
0,1,LSE When did Aniket get so big and str,NaN,1st,2nd,1st,1st,2nd,13,810,3,2
1,2,The ideal of a platonic relationsh,NaN,1st,1st,1st,3rd,1st,13,804,4,0
2,3,ANU Guangzhou Mama,NaN,1st,2nd,1st,2nd,1st,13,802,3,2
3,4,Cambridge B,NaN,1st,1st,3rd,2nd,1st,12,809,3,1
4,5,KCL It’s not clocking to you that I am,NaN,1st,1st,4th,1st,1st,12,801,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1010,team,result,side,adjudicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
def create_teamtab(df):
    # Find the index of the row with the known value
    stop_index = df[df['Rk'] == 'Rk'].index[0]
    teamtab = df.iloc[:stop_index]
    #Remove useless data
    target_column = 'Spk'
    column_index = teamtab.columns.get_loc(target_column)

    # Slice the DataFrame to keep columns up to and including the target column
    teamtab = teamtab.iloc[:, :column_index + 1]
    df2 = df.drop(teamtab.index)
    df2.reset_index(drop=True, inplace=True)
    return teamtab, df2

def create_speakertab(df2):
    stop_index2 = df2[df2['Rk'] == 'team'].index[0]
    speakertab = df2.iloc[:stop_index2]

    #remove top row & reset index:
    speakertab = speakertab.iloc[1:].reset_index(drop=True)  
    #Remove useless data
    target_column = 'Spk'
    column_index = speakertab.columns.get_loc(target_column)
    speakertab = speakertab.rename(columns={'Rk': 'SpeakRank','team':'speaker','R1':'team'})
    
    
    # Get the first 4 and last column names
    first_columns = speakertab.columns[:4].tolist()
    last_column = speakertab.columns[-1]

    # Get the middle columns that need renaming
    #These will be the round results
    middle_columns = speakertab.columns[4:-1]

    # Create new names for the middle columns (e.g., 'NewCol1', 'NewCol2', ...)
    new_middle_columns = [f'R{i}' for i in range(1, len(middle_columns) + 1)]

    # Combine the first columns, renamed middle columns, and last column
    new_columns = first_columns + new_middle_columns + [last_column]

    # Apply the new column names to the DataFrame
    speakertab.columns = new_columns
    
    df3 = df2.drop(speakertab.index)
    df3 = df3.iloc[1:].reset_index(drop=True)
    df3.reset_index(drop=True, inplace=True)
    
    return speakertab, df3