I want to have

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# List only files in the current directory
files = [f for f in os.listdir('.') if os.path.isfile(f)]

for f in files:
    print(f)
    
txt_files = [f for f in files if f.lower().endswith('.txt')]

print(txt_files)

Cambridge IV 2024 (22 rooms).txt
Eristic BPD (25 rms).txt
Hart House Intervasity 2024 (25rms).txt
Kampala open 3.0 (25 rms).txt
Kumasi Debate Open 2024 (21 rms).txt
Macau Debate Open 2025(23 rms).txt
Malaysia Online Debate Open 2025（25 rms）.txt
Osaka IV 2024 (21 rms).txt
Oxford IV 2024 (28 rms).txt
Princeton IV 2024 (32 rms).txt
Scrape_tab_to_txt.ipynb
Shanghai International Debate Open 2025(38 rms).txt
Shri Ram Pre ABP (20 rms).txt
St Andrew's Pre-EUDC 2025.txt
St Andrews Pre-EUDC Competition (20 rms).txt
Tab2Database.ipynb
Tab2Database2.ipynb
The Delhi Debate 2024 (21 rms).txt
Tournament_masterlist.xlsx
Uhuru Worlds 2025 (83 rms).txt
Vienna IV 2025 (22rms).txt
Vienna Online Open Pre-EUDC 2024 (27 rms).txt
Vienna Online Open Pre-WUDC 2024 (32rms).txt
Warwick Pre-EUDC 2025 (29 rms).txt
Warwick Pre-EUDC 2025 (29 rms)_rounds_done.xlsx
Warwick Pre-EUDC 2025 (29 rms)_speakertab_done.xlsx
Warwick Pre-EUDC 2025 (29 rms)_teamtab_done.xlsx
['Cambridge IV 2024 (22 rooms).txt', 'Eristic BPD (25 rms).txt', 'Hart House Intervasity 2024 (25rms).txt', 'Kampala open 3.0 (25 rms).txt', 'Kumasi Debate Open 2024 (21 rms).txt', 'Macau Debate Open 2025(23 rms).txt', 'Malaysia Online Debate Open 2025（25 rms）.txt', 'Osaka IV 2024 (21 rms).txt', 'Oxford IV 2024 (28 rms).txt', 'Princeton IV 2024 (32 rms).txt', 'Shanghai International Debate Open 2025(38 rms).txt', 'Shri Ram Pre ABP (20 rms).txt', "St Andrew's Pre-EUDC 2025.txt", 'St Andrews Pre-EUDC Competition (20 rms).txt', 'The Delhi Debate 2024 (21 rms).txt', 'Uhuru Worlds 2025 (83 rms).txt', 'Vienna IV 2025 (22rms).txt', 'Vienna Online Open Pre-EUDC 2024 (27 rms).txt', 'Vienna Online Open Pre-WUDC 2024 (32rms).txt', 'Warwick Pre-EUDC 2025 (29 rms).txt']

# Start: Goal
##### Debate Project
The goal of this project is to use programming to enhance the level of competitive academic debating, mostly by doing advanced data-analysis and further techniques.

##### Tabdata
A huge chapter in this is the creation of a comprehensive debate database, that includes all elements of debating that can be used to measure, evaluate, and increase performance. At this junction of the project the **TabData** project tries to set up the database of debates and some follow-up metrics, such as "elo-score". 

##### Tabdata useage
In ideal case this can be used for predicting winners of debates, predicting and analyzing biases and outliers with motions, judges, speaker-scores of certain judges, hardships with motion-types, correlations between outcomes in debate tournaments, or just providing an overview about the long-term trends within debating by having a comprehensive data through a long cross-section of time. 

# About the data
Our data arrives in a csv. <span style="color:red">**At this test programme, it is manually downloaded**</span>  but for future tournament databases, it will be downloaded by scraping with Selenium.

The data consists the outcomes of debate tournaments. This has 3 main sections. 

#### Team tab ####
The teamtab consists the teams that participated at the tournament, and the ranking between the teams at the end of the tournament's preliminary rounds. As a rule of thumb, tournaments run for 5 rounds, but major tournaments such as European or World Championships have 9 preliminary rounds. The top teams go through to the elimination rounds, to reach, and eventually win the finals. Teams that do not reach the playoffs, are ranked by their respective positions in the tab. 

For example, if there are 40 teams in a tournament, the top 8 will go to the semi-finals, with a preset seeding in British Parliamentary debates where in Semi-Final-1 the 1st, 4th, 5th, and 8th seeded teams debate, and in Semi-Final-2 the 2nd, 3rd, 6th, 7th seeded teams debate. Each semi-final will have 2 teams that advance to the finals. So, despite teams do not carry the resulst to the outrounds, they have an impact on each team's result. Teams 9-40 are ranked based on their positions within the tab. 

#### Speaker tab ####
In the same csv, following the teamtab, comes the speakertab. While the teamtab is ranking teams, the speakertab ranks the individual speakers within a debate tournaments. Because in British Parliamentary debating the speaker score of the individual speakers within a debate is summed, and teams are ranked in the order of the sum of these scores, teamtab and speakertab strongly correlates, but they don't have to be the same. Furthermore, it provides further ways to analyse data for us. Both the teamtab and the spakertab is with their own headers within the data, therefore slicing up the csv to teamtab and speakertab is not particularly complex.

#### Debate results ####
The third, and largest part of the csv consists each team's result within a given debate, and also the role they had (f.e. Opening Government) and the adjucating judges too. Each row consists the data for each individual team's separate round. 

Each round was obtained separately and attached to the csv, so every round has its own headers, that is needed, because the data does not consist the roundnumbers themselves.

The data looks something like this: 
| team              | result | side    | adjudicators  |
| :---------------- | :------: | ----: | --------------|
| Team1        |  1st   | Opening Government | Judge1,Judge2 |  
| Team2           |  1st   | Opening Government | Judge3 |
| Team3    |  2nd   | Closing Opposition |  Judge4,Judge6 |
| Team4 |  4th   | Opening Opposition | Judge3 |

From the data we can see that Team 2 and Team 4 debated in the same debate at the given round, because they had the same adjudicators. (Judge 3). *Team2* finished 2nd, and *Team4* finished 4th. This itself is not new information, because we could retrieve this information from the teamtab. However, the teamtab provides no information on the opponents, and the speaker scores the team have received. 


#### The task #### 
The teamtab, the speakertab, and the debate_results dataframes are connected by 1 common column: the team's names. Each tournament, each team has its unique name. However, it is possible for John Blue to run in the team "Blue Brothers" in 1 tournament, with his sibling Adam Blue, and run with a different teamname at a following tournament, with a different teammate, or the very same. Therefore, the hardest part once the database is created is to clear out the database from people with similar names. Fortunately, most of the times debaters have unique names. As a matter of fact, the teamtab is not even needed for the creation of the "debate-level" dataframe. 

So, for each row of debate results, we are first going to retrieve the speaker scores and the speakers for the team from the speakertab. Then we will group the 4 debating teams together to one row. And finally, we will separate each adjudicator to a different row. This will give us 1 row of data in our phenomenal database.

## Start: Read in data ##

In [69]:
def get_comp_name(txt_file):
    comp_name = txt_file[:-4]
    print(comp_name)
    df = pd.read_csv(txt_file, delimiter ='\t', on_bad_lines='warn')
    print(len(df))
    return df, comp_name

data = pd.DataFrame()

for i in range(len(txt_files)):
    df, comp_name = get_comp_name(txt_files[i])
df

Cambridge IV 2024 (22 rooms)

FileNotFoundError: [Errno 2] No such file or directory: 'Cambridge IV 2024 (22 rooms).txt'

In [38]:
df[200:300]

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
200,75=,Myra Kong,ESL,We debate best in grocery store ai,77,79,78,81,72,387,77.40,3.01
201,75=,Max Gasslitter Strobl,ESL,DM Spiritual Slut and German Dad,76,81,76,77,77,387,77.40,1.85
202,75=,cal birtley,NaN,Aberdeen BW… (B)ut not the one you,78,78,77,77,77,387,77.40,0.49
203,75=,Na’ama Benamy,ESL,KU Mandatory military dropouts,80,77,78,72,80,387,77.40,2.94
204,75=,Jake O&#x27;Loughlin,NaN,UCD L&amp;H E(veryone else was unavail,78,78,76,76,79,387,77.40,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...
295,166=,Jonathan Krapp,ESL,DAV Aachen YJ,78,73,74,73,76,374,74.80,1.94
296,166=,Eric Peng,Novice,please i just want to go,75,74,74,75,76,374,74.80,0.75
297,173=,Krishaan Doctor,"ESL, Novice",SoBo Crusaders,72,76,72,77,75,372,74.40,2.06
298,173=,Paulina Šalkauskaitė,Novice,are we picking a team name or are,75,75,74,74,74,372,74.40,0.49
299,173=,Athang Shinde,ESL,Cooper House - Perseverance in Per,76,76,71,75,74,372,74.40,1.85

## I. Teamtab ##
First, we need to create the teamtab

In [39]:
# Find the index of the row with the known value
stop_index = df[df['Rk'] == 'Rk'].index[0]

In [40]:
stop_index

124

In [41]:
teamtab = df.iloc[:stop_index]
teamtab

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
0,1,LSE When did Aniket get so big and str,NaN,1st,2nd,1st,1st,2nd,13,810,3,2
1,2,The ideal of a platonic relationsh,NaN,1st,1st,1st,3rd,1st,13,804,4,0
2,3,ANU Guangzhou Mama,NaN,1st,2nd,1st,2nd,1st,13,802,3,2
3,4,Cambridge B,NaN,1st,1st,3rd,2nd,1st,12,809,3,1
4,5,KCL It’s not clocking to you that I am,NaN,1st,1st,4th,1st,1st,12,801,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
119,120,SWING 5,NaN,—,—,—,4th,—,0,133,0,0
120,121=,AU Taanish Arora,ESL,—,—,—,—,—,—,—,0,0
121,121=,UWI A,NaN,—,—,—,—,—,—,—,0,0
122,121=,Becky and Adika,ESL,—,—,—,—,—,—,—,0,0
123,121=,UTJ B,NaN,—,—,—,—,—,—,—,0,0

In [42]:
#Remove useless data
target_column = 'Spk'
column_index = teamtab.columns.get_loc(target_column)

# Slice the DataFrame to keep columns up to and including the target column
teamtab = teamtab.iloc[:, :column_index + 1]
teamtab

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk
0,1,LSE When did Aniket get so big and str,NaN,1st,2nd,1st,1st,2nd,13,810
1,2,The ideal of a platonic relationsh,NaN,1st,1st,1st,3rd,1st,13,804
2,3,ANU Guangzhou Mama,NaN,1st,2nd,1st,2nd,1st,13,802
3,4,Cambridge B,NaN,1st,1st,3rd,2nd,1st,12,809
4,5,KCL It’s not clocking to you that I am,NaN,1st,1st,4th,1st,1st,12,801
...,...,...,...,...,...,...,...,...,...,...
119,120,SWING 5,NaN,—,—,—,4th,—,0,133
120,121=,AU Taanish Arora,ESL,—,—,—,—,—,—,—
121,121=,UWI A,NaN,—,—,—,—,—,—,—
122,121=,Becky and Adika,ESL,—,—,—,—,—,—,—
123,121=,UTJ B,NaN,—,—,—,—,—,—,—

In [43]:
df2 = df.drop(teamtab.index)
df2.reset_index(drop=True, inplace=True)
df2

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
0,Rk,name,category,team,R1,R2,R3,R4,R5,Total,Avg,Stdev
1,1,Shaurya Chandravanshi,NaN,The ideal of a platonic relationsh,80,82,83,82,82,409,81.80,0.98
2,2=,Fraser McConachie,NaN,Cambridge B,81,81,79,81,83,405,81.00,1.26
3,2=,Sachin Tissera,ESL,LSE When did Aniket get so big and str,80,80,81,84,80,405,81.00,1.55
4,2=,Arjun Gunalan,NaN,LSE When did Aniket get so big and str,80,81,81,83,80,405,81.00,1.10
...,...,...,...,...,...,...,...,...,...,...,...,...
886,team,result,side,adjudicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## II. The speaker tab

In [44]:
stop_index2 = df2[df2['Rk'] == 'team'].index[0]
speakertab = df2.iloc[:stop_index2]

#remove top row & reset index:
speakertab = speakertab.iloc[1:].reset_index(drop=True)
speakertab

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
0,1,Shaurya Chandravanshi,NaN,The ideal of a platonic relationsh,80,82,83,82,82,409,81.80,0.98
1,2=,Fraser McConachie,NaN,Cambridge B,81,81,79,81,83,405,81.00,1.26
2,2=,Sachin Tissera,ESL,LSE When did Aniket get so big and str,80,80,81,84,80,405,81.00,1.55
3,2=,Arjun Gunalan,NaN,LSE When did Aniket get so big and str,80,81,81,83,80,405,81.00,1.10
4,5=,Olivia Arbour,NaN,Cambridge B,81,81,80,80,82,404,80.80,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...
241,233=,Speaker 2,NaN,swing 1,—,—,—,—,—,—,—,—
242,233=,Speaker 2,NaN,swing 2,—,—,—,—,—,—,—,—
243,233=,Speaker 2,NaN,swing 3,—,—,—,—,—,—,—,—
244,233=,Speaker 2,NaN,SWING 4,—,—,—,—,—,—,—,—
245,233=,Speaker 2,NaN,SWING 5,—,—,—,—,—,—,—,—

In [45]:
#Remove useless data
target_column = 'Spk'
column_index = speakertab.columns.get_loc(target_column)

# Slice the DataFrame to keep columns up to and including the target column
speakertab = speakertab.iloc[:, :column_index + 1]
speakertab

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk
0,1,Shaurya Chandravanshi,NaN,The ideal of a platonic relationsh,80,82,83,82,82,409
1,2=,Fraser McConachie,NaN,Cambridge B,81,81,79,81,83,405
2,2=,Sachin Tissera,ESL,LSE When did Aniket get so big and str,80,80,81,84,80,405
3,2=,Arjun Gunalan,NaN,LSE When did Aniket get so big and str,80,81,81,83,80,405
4,5=,Olivia Arbour,NaN,Cambridge B,81,81,80,80,82,404
...,...,...,...,...,...,...,...,...,...,...
241,233=,Speaker 2,NaN,swing 1,—,—,—,—,—,—
242,233=,Speaker 2,NaN,swing 2,—,—,—,—,—,—
243,233=,Speaker 2,NaN,swing 3,—,—,—,—,—,—
244,233=,Speaker 2,NaN,SWING 4,—,—,—,—,—,—
245,233=,Speaker 2,NaN,SWING 5,—,—,—,—,—,—

In [46]:
speakertab = speakertab.rename(columns={'Rk': 'SpeakRank','team':'speaker','R1':'team'})
speakertab

,SpeakRank,speaker,categories,team,R2,R3,R4,R5,Pts,Spk
0,1,Shaurya Chandravanshi,NaN,The ideal of a platonic relationsh,80,82,83,82,82,409
1,2=,Fraser McConachie,NaN,Cambridge B,81,81,79,81,83,405
2,2=,Sachin Tissera,ESL,LSE When did Aniket get so big and str,80,80,81,84,80,405
3,2=,Arjun Gunalan,NaN,LSE When did Aniket get so big and str,80,81,81,83,80,405
4,5=,Olivia Arbour,NaN,Cambridge B,81,81,80,80,82,404
...,...,...,...,...,...,...,...,...,...,...
241,233=,Speaker 2,NaN,swing 1,—,—,—,—,—,—
242,233=,Speaker 2,NaN,swing 2,—,—,—,—,—,—
243,233=,Speaker 2,NaN,swing 3,—,—,—,—,—,—
244,233=,Speaker 2,NaN,SWING 4,—,—,—,—,—,—
245,233=,Speaker 2,NaN,SWING 5,—,—,—,—,—,—

In [47]:
# Get the first 4 and last column names
first_columns = speakertab.columns[:4].tolist()
last_column = speakertab.columns[-1]

# Get the middle columns that need renaming
#These will be the round results
middle_columns = speakertab.columns[4:-1]

# Create new names for the middle columns (e.g., 'NewCol1', 'NewCol2', ...)
new_middle_columns = [f'R{i}' for i in range(1, len(middle_columns) + 1)]

# Combine the first columns, renamed middle columns, and last column
new_columns = first_columns + new_middle_columns + [last_column]

# Apply the new column names to the DataFrame
speakertab.columns = new_columns

speakertab

,SpeakRank,speaker,categories,team,R1,R2,R3,R4,R5,Spk
0,1,Shaurya Chandravanshi,NaN,The ideal of a platonic relationsh,80,82,83,82,82,409
1,2=,Fraser McConachie,NaN,Cambridge B,81,81,79,81,83,405
2,2=,Sachin Tissera,ESL,LSE When did Aniket get so big and str,80,80,81,84,80,405
3,2=,Arjun Gunalan,NaN,LSE When did Aniket get so big and str,80,81,81,83,80,405
4,5=,Olivia Arbour,NaN,Cambridge B,81,81,80,80,82,404
...,...,...,...,...,...,...,...,...,...,...
241,233=,Speaker 2,NaN,swing 1,—,—,—,—,—,—
242,233=,Speaker 2,NaN,swing 2,—,—,—,—,—,—
243,233=,Speaker 2,NaN,swing 3,—,—,—,—,—,—
244,233=,Speaker 2,NaN,SWING 4,—,—,—,—,—,—
245,233=,Speaker 2,NaN,SWING 5,—,—,—,—,—,—

## III. Connecting the speakertab & Debate Results

In [48]:
df3 = df2.drop(speakertab.index)
df3 = df3.iloc[1:].reset_index(drop=True)
df3.reset_index(drop=True, inplace=True)
df3

,Rk,team,categories,R1,R2,R3,R4,R5,Pts,Spk,1sts,2nds
0,team,result,side,ballot,adjudicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LSE C,2nd,Opening Government,View Ballot,"Maša PopeskovićⒸ , Matheus Furtado",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LSE When did Aniket get so big and str,1st,Opening Opposition,View Ballot,"Maša PopeskovićⒸ , Matheus Furtado",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SoBo Crusaders,4th,Closing Government,View Ballot,"Maša PopeskovićⒸ , Matheus Furtado",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4 am start :smile: 3 am start :cry,3rd,Closing Opposition,View Ballot,"Maša PopeskovićⒸ , Matheus Furtado",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
639,team,result,side,adjudicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df3.loc[df3['R1'] == 'View Ballot', 'R1'] = df3['R2']
df3 = df3.iloc[:,:4]
df3["Round"] = 0
df3

C:\Users\andra\AppData\Local\Temp\ipykernel_36628\1722710906.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["Round"] = 0

,Rk,team,categories,R1,Round
0,team,result,side,ballot,0
1,LSE C,2nd,Opening Government,"Maša PopeskovićⒸ , Matheus Furtado",0
2,LSE When did Aniket get so big and str,1st,Opening Opposition,"Maša PopeskovićⒸ , Matheus Furtado",0
3,SoBo Crusaders,4th,Closing Government,"Maša PopeskovićⒸ , Matheus Furtado",0
4,4 am start :smile: 3 am start :cry,3rd,Closing Opposition,"Maša PopeskovićⒸ , Matheus Furtado",0
...,...,...,...,...,...
639,team,result,side,adjudicators,0
640,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",0
641,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",0
642,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",0
643,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",0

In [50]:
round_counter = 0
row_numbers = df3.index[df3["Rk"] == "team"].tolist()

#Trick "dumbass": In order for the next for loop to iterate through, I append a 0 to the end of my list. 
#This is needed, so when the loop is at the last round of the we don't end up with referring to a roundnumber, that would be 
#Larger than the last element in the list. 
#What I mean: check a few lines down
row_numbers.append(0)
print(row_numbers)


df4 = df3
for i in df4.index:
    if row_numbers[round_counter] == i:
        print(i)
        print(round_counter)
        
        #Trick "dumbass" --> in the last round if I did not append a 0, row_umbers[round_counter] would be
        #larger than the last element's position in the row_numbers list
        #But things just work perfectly this way, like a shitty spagetthi
        round_counter += 1
    df4.loc[i, "Round"] = round_counter  # Example logic
row_numbers = row_numbers[:-1]
df4

[0, 117, 234, 351, 468, 577, 594, 611, 620, 625, 634, 639, 0]
0
0
117
1
234
2
351
3
468
4
577
5
594
6
611
7
620
8
625
9
634
10
639
11

,Rk,team,categories,R1,Round
0,team,result,side,ballot,1
1,LSE C,2nd,Opening Government,"Maša PopeskovićⒸ , Matheus Furtado",1
2,LSE When did Aniket get so big and str,1st,Opening Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1
3,SoBo Crusaders,4th,Closing Government,"Maša PopeskovićⒸ , Matheus Furtado",1
4,4 am start :smile: 3 am start :cry,3rd,Closing Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1
...,...,...,...,...,...
639,team,result,side,adjudicators,12
640,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
641,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
642,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
643,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12

In [51]:
df4.head(20)

,Rk,team,categories,R1,Round
0,team,result,side,ballot,1
1,LSE C,2nd,Opening Government,"Maša PopeskovićⒸ , Matheus Furtado",1
2,LSE When did Aniket get so big and str,1st,Opening Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1
3,SoBo Crusaders,4th,Closing Government,"Maša PopeskovićⒸ , Matheus Furtado",1
4,4 am start :smile: 3 am start :cry,3rd,Closing Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1
5,Kimbhut Kimakar,4th,Opening Government,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",1
6,KU Mandatory military dropouts,2nd,Opening Opposition,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",1
7,Warwick This House Would Break (But Not Up,3rd,Closing Government,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",1
8,Why does Hilary have an Australian,1st,Closing Opposition,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",1
9,surely we will wake up,2nd,Opening Government,"ilijaⒸ , Ngo Nguyen Minh Tu",1
10,More boobs than brains,1st,Opening Opposition,"ilijaⒸ , Ngo Nguyen Minh Tu",1
11,DU raam bharose aaye hai,3rd,Closing Government,"ilijaⒸ , Ngo Nguyen Minh Tu",1
12,Ito Atsuki Fan Club 😘💕❤️,4th,Closing Opposition,"ilijaⒸ , Ngo Nguyen Minh Tu",1
13,Woodstock Reserve,4th,Opening Government,"Pjotr KosterⒸ , Aaryav Bansal , Advika SharmaⓉ",1
14,Cambridge B,1st,Opening Opposition,"Pjotr KosterⒸ , Aaryav Bansal , Advika SharmaⓉ",1
15,he’s got me by the marbles,3rd,Closing Government,"Pjotr KosterⒸ , Aaryav Bansal , Advika SharmaⓉ",1
16,IITB Chakraborty &amp; Raghav Raj,2nd,Closing Opposition,"Pjotr KosterⒸ , Aaryav Bansal , Advika SharmaⓉ",1
17,MCU A,4th,Opening Government,"Krishaang KohliⒸ , Ellen Roper , Wajeeh",1
18,Zhu-ko &amp; Hum-iroh take on Ba Sing,1st,Opening Opposition,"Krishaang KohliⒸ , Ellen Roper , Wajeeh",1
19,"Ethos, pathos... what&#x27;s the third",2nd,Closing Government,"Krishaang KohliⒸ , Ellen Roper , Wajeeh",1

In [52]:
df4.tail(20)

,Rk,team,categories,R1,Round
624,Cambridge B,eliminated,Closing Opposition,"ilijaⒸ , Ellie Middleton , Emma Walker , Harve...",9
625,team,result,side,adjudicators,10
626,Potsdam A-Z,advancing,Opening Government,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",10
627,Djorđa Kratovca 65/8 parking spot,advancing,Opening Opposition,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",10
628,DKW Vienna (A)mbulance,eliminated,Closing Government,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",10
629,UP Manila VR,eliminated,Closing Opposition,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",10
630,AUBG A,advancing,Opening Government,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",10
631,Wiseman and the Tribal Chief,eliminated,Opening Opposition,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",10
632,DKW B(aking Bread),advancing,Closing Government,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",10
633,IITB Chakraborty &amp; Raghav Raj,eliminated,Closing Opposition,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",10
634,team,result,side,adjudicators,11
635,DKW B(aking Bread),advancing,Opening Government,"William SmithⒸ , Jim Balatos , John Washburn ,...",11
636,AUBG A,eliminated,Opening Opposition,"William SmithⒸ , Jim Balatos , John Washburn ,...",11
637,Djorđa Kratovca 65/8 parking spot,eliminated,Closing Government,"William SmithⒸ , Jim Balatos , John Washburn ,...",11
638,Potsdam A-Z,eliminated,Closing Opposition,"William SmithⒸ , Jim Balatos , John Washburn ,...",11
639,team,result,side,adjudicators,12
640,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
641,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
642,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12
643,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12

In [53]:
df7 = df4
df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
for i in df7.index:
    #print(df7.Rk[i])
    loop_speaker1 = 'iron/swing'
    loop_speaker2 = 'iron/swing'
    loop_speaker1_score = 0
    loop_speaker2_score = 0
    loop_round = df7.Round[i]
    for j in speakertab.index:
        if df7.Rk[i] == speakertab.team[j]:
            if loop_speaker1 == 'iron/swing':
                loop_speaker1 = speakertab.speaker[j]
                if df7.team[i] == '1st' or df7.team[i] == '2nd' or df7.team[i] == '3rd' or df7.team[i] == '4th':
                    loop_speaker1_score = speakertab.iat[j,3+loop_round]
                else:
                    loop_speaker1_score = 'outround'
            else:
                loop_speaker2 = speakertab.speaker[j]
                if df7.team[i] == '1st' or df7.team[i] == '2nd' or df7.team[i] == '3rd' or df7.team[i] == '4th':
                    loop_speaker2_score = speakertab.iat[j,3+loop_round]
                else:
                    loop_speaker2_score = 'outround'
    df7.Speaker1[i] = loop_speaker1
    df7.Speaker2[i] = loop_speaker2
    df7.Speaker1_score[i] = loop_speaker1_score
    df7.Speaker2_score[i] = loop_speaker2_score
df7

C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['Speaker1'], df7['Speaker2'],df7['Speaker1_score'], df7['Speaker2_score'], df7['Comp_name'] = 0,0,0,0,comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.Speaker1[i] = loop_speaker1
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.Speaker2[i] = loop_speaker2
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.Speaker1_score[i] = loop_speaker1_score
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\973372616.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.Speaker2_score[i] = loop_speaker2_score

,Rk,team,categories,R1,Round,Speaker1,Speaker2,Speaker1_score,Speaker2_score,Comp_name
0,team,result,side,ballot,1,iron/swing,iron/swing,0,0,Warwick Pre-EUDC 2025 (29 rms)
1,LSE C,2nd,Opening Government,"Maša PopeskovićⒸ , Matheus Furtado",1,Michele Liu,Rayaan Aly Khan,80,78,Warwick Pre-EUDC 2025 (29 rms)
2,LSE When did Aniket get so big and str,1st,Opening Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1,Sachin Tissera,Arjun Gunalan,80,80,Warwick Pre-EUDC 2025 (29 rms)
3,SoBo Crusaders,4th,Closing Government,"Maša PopeskovićⒸ , Matheus Furtado",1,Krishaan Doctor,Pramit Rao,72,72,Warwick Pre-EUDC 2025 (29 rms)
4,4 am start :smile: 3 am start :cry,3rd,Closing Opposition,"Maša PopeskovićⒸ , Matheus Furtado",1,Nyx Kucharski,Bilguun Tserenbadral,76,73,Warwick Pre-EUDC 2025 (29 rms)
...,...,...,...,...,...,...,...,...,...,...
639,team,result,side,adjudicators,12,iron/swing,iron/swing,0,0,Warwick Pre-EUDC 2025 (29 rms)
640,UWODS Revealed Preference for Suffering,advancing,Opening Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12,Kevin Chen,Jasmeet Randhawa,outround,outround,Warwick Pre-EUDC 2025 (29 rms)
641,GUU (C)an you spot the difference?,eliminated,Opening Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12,Harry Braid,Jamie Ghosh,outround,outround,Warwick Pre-EUDC 2025 (29 rms)
642,DU raam bharose aaye hai,eliminated,Closing Government,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12,divyanshi dusad,Bhavisya sharma,outround,outround,Warwick Pre-EUDC 2025 (29 rms)
643,Aberdeen Don&#x27;t ask us about the balkans,eliminated,Closing Opposition,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",12,Stanley Wilcox,Chloe Stevenson,outround,outround,Warwick Pre-EUDC 2025 (29 rms)

## IV. Grouping the teambased result data up to debate based result data

In [54]:
df8 = df7
df8

grouped = df8.groupby(['Round', 'R1']).agg(list).reset_index()

# Flatten the grouped DataFrame by splitting the lists into separate columns
# Here, we use the `apply(pd.Series)` to convert each list into a separate column
grouped_expanded = pd.concat([grouped[['Round', 'R1']], 
                              grouped['Rk'].apply(pd.Series), 
                              grouped['categories'].apply(pd.Series), 
                              grouped['team'].apply(pd.Series),
                              grouped['Speaker1'].apply(pd.Series),
                              grouped['Speaker2'].apply(pd.Series),
                              grouped['Speaker1_score'].apply(pd.Series),
                              grouped['Speaker2_score'].apply(pd.Series)], axis=1)

# Rename the columns to match the desired output

In [55]:
grouped_expanded.columns = ['Round', 'Panel', 
                            'Team1', 'Team2', 'Team3', 'Team4',
                            'Team1 position', 'Team2 position', 'Team3 position', 'Team4 position',
                            'Team1 result', 'Team2 result', 'Team3 result', 'Team4 result',
                            'T1_S1 name', 'T2_S1 name', 'T3_S1 name', 'T4_S1 name',
                            'T1_S2 name', 'T2_S2 name', 'T3_S2 name', 'T4_S2 name',
                            'T1_S1 score', 'T2_S1 score', 'T3_S1 score', 'T4_S1 score',
                            'T1_S2 score', 'T2_S2 score', 'T3_S2 score', 'T4_S2 score']

In [56]:
grouped_expanded

,Round,Panel,Team1,Team2,Team3,Team4,Team1 position,Team2 position,Team3 position,Team4 position,...,T3_S2 name,T4_S2 name,T1_S1 score,T2_S1 score,T3_S1 score,T4_S1 score,T1_S2 score,T2_S2 score,T3_S2 score,T4_S2 score
0,1,Alex MartinⒸ,ANU Guangzhou Mama,A fossil was coaxed out of retirem,HH political overreach into my pants,"Chicago That&#x27;s GBP, the price go up if it...",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Felix Zhang,Victoria Kurakata,81,76,78,79,81,76,76,80
1,1,"AmitaiⒸ , Maja Patynowska , Jim BalatosⓉ",DM Hella Adorable,AUBG A,Edinburgh where&#x27;s wurdaan,"E ne le jarabi l&#x27;i la, too much",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Wurdaan Kashif,Nimai Koneru,80,79,80,80,80,77,—,82
2,1,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",Kimbhut Kimakar,KU Mandatory military dropouts,Warwick This House Would Break (But Not Up,Why does Hilary have an Australian,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Toby Ford,Henrietta Vanni,76,80,77,81,76,79,77,80
3,1,"Ellie MiddletonⒸ , Azwad Abdullah AyanⓉ",UCL Rick and Morty Season 2,SPSU SPbU A,GUU (C)an you spot the difference?,This debate? Gnarly,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Jamie Ghosh,Summer,81,76,74,73,81,75,74,73
4,1,Emma WalkerⒸ,Chen &amp; Qiu,Our Opening is Weak but We Finish S,THUJ HUJI M&amp;S,PUCP Ezeta &amp; Nuñez del Prado,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Michael Khalfin,Diego Nuñez del Prado Velarde,79,74,75,76,79,72,74,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,10,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
166,11,"William SmithⒸ , Jim Balatos , John Washburn ,...",DKW B(aking Bread),AUBG A,Djorđa Kratovca 65/8 parking spot,Potsdam A-Z,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Katarina Lazić,Juliette Scheuing,outround,outround,outround,outround,outround,outround,outround,outround
167,11,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
168,12,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",UWODS Revealed Preference for Suffering,GUU (C)an you spot the difference?,DU raam bharose aaye hai,Aberdeen Don&#x27;t ask us about the balkans,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Bhavisya sharma,Chloe Stevenson,outround,outround,outround,outround,outround,outround,outround,outround
169,12,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [57]:
df9 = grouped_expanded
df9

,Round,Panel,Team1,Team2,Team3,Team4,Team1 position,Team2 position,Team3 position,Team4 position,...,T3_S2 name,T4_S2 name,T1_S1 score,T2_S1 score,T3_S1 score,T4_S1 score,T1_S2 score,T2_S2 score,T3_S2 score,T4_S2 score
0,1,Alex MartinⒸ,ANU Guangzhou Mama,A fossil was coaxed out of retirem,HH political overreach into my pants,"Chicago That&#x27;s GBP, the price go up if it...",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Felix Zhang,Victoria Kurakata,81,76,78,79,81,76,76,80
1,1,"AmitaiⒸ , Maja Patynowska , Jim BalatosⓉ",DM Hella Adorable,AUBG A,Edinburgh where&#x27;s wurdaan,"E ne le jarabi l&#x27;i la, too much",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Wurdaan Kashif,Nimai Koneru,80,79,80,80,80,77,—,82
2,1,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",Kimbhut Kimakar,KU Mandatory military dropouts,Warwick This House Would Break (But Not Up,Why does Hilary have an Australian,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Toby Ford,Henrietta Vanni,76,80,77,81,76,79,77,80
3,1,"Ellie MiddletonⒸ , Azwad Abdullah AyanⓉ",UCL Rick and Morty Season 2,SPSU SPbU A,GUU (C)an you spot the difference?,This debate? Gnarly,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Jamie Ghosh,Summer,81,76,74,73,81,75,74,73
4,1,Emma WalkerⒸ,Chen &amp; Qiu,Our Opening is Weak but We Finish S,THUJ HUJI M&amp;S,PUCP Ezeta &amp; Nuñez del Prado,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Michael Khalfin,Diego Nuñez del Prado Velarde,79,74,75,76,79,72,74,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,10,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
166,11,"William SmithⒸ , Jim Balatos , John Washburn ,...",DKW B(aking Bread),AUBG A,Djorđa Kratovca 65/8 parking spot,Potsdam A-Z,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Katarina Lazić,Juliette Scheuing,outround,outround,outround,outround,outround,outround,outround,outround
167,11,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
168,12,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",UWODS Revealed Preference for Suffering,GUU (C)an you spot the difference?,DU raam bharose aaye hai,Aberdeen Don&#x27;t ask us about the balkans,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Bhavisya sharma,Chloe Stevenson,outround,outround,outround,outround,outround,outround,outround,outround
169,12,adjudicators,team,NaN,NaN,NaN,side,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [58]:
df9 = df9.drop(df9[df9['Team1'] == 'team'].index)
df9 = df9.reset_index()
df9 = df9.drop('index', axis=1)
df9

,Round,Panel,Team1,Team2,Team3,Team4,Team1 position,Team2 position,Team3 position,Team4 position,...,T3_S2 name,T4_S2 name,T1_S1 score,T2_S1 score,T3_S1 score,T4_S1 score,T1_S2 score,T2_S2 score,T3_S2 score,T4_S2 score
0,1,Alex MartinⒸ,ANU Guangzhou Mama,A fossil was coaxed out of retirem,HH political overreach into my pants,"Chicago That&#x27;s GBP, the price go up if it...",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Felix Zhang,Victoria Kurakata,81,76,78,79,81,76,76,80
1,1,"AmitaiⒸ , Maja Patynowska , Jim BalatosⓉ",DM Hella Adorable,AUBG A,Edinburgh where&#x27;s wurdaan,"E ne le jarabi l&#x27;i la, too much",Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Wurdaan Kashif,Nimai Koneru,80,79,80,80,80,77,—,82
2,1,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",Kimbhut Kimakar,KU Mandatory military dropouts,Warwick This House Would Break (But Not Up,Why does Hilary have an Australian,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Toby Ford,Henrietta Vanni,76,80,77,81,76,79,77,80
3,1,"Ellie MiddletonⒸ , Azwad Abdullah AyanⓉ",UCL Rick and Morty Season 2,SPSU SPbU A,GUU (C)an you spot the difference?,This debate? Gnarly,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Jamie Ghosh,Summer,81,76,74,73,81,75,74,73
4,1,Emma WalkerⒸ,Chen &amp; Qiu,Our Opening is Weak but We Finish S,THUJ HUJI M&amp;S,PUCP Ezeta &amp; Nuñez del Prado,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Michael Khalfin,Diego Nuñez del Prado Velarde,79,74,75,76,79,72,74,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,9,"ilijaⒸ , Ellie Middleton , Emma Walker , Harve...",LSE When did Aniket get so big and str,quarter life crisis brought us bac,ANU Guangzhou Mama,Cambridge B,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Elanor Parkinson,Olivia Arbour,outround,outround,outround,outround,outround,outround,outround,outround
154,10,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",AUBG A,Wiseman and the Tribal Chief,DKW B(aking Bread),IITB Chakraborty &amp; Raghav Raj,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Mira Eberdorfer,Pranjal Chakraborty,outround,outround,outround,outround,outround,outround,outround,outround
155,10,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",Potsdam A-Z,Djorđa Kratovca 65/8 parking spot,DKW Vienna (A)mbulance,UP Manila VR,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Anton Gonta,Raffy Perez,outround,outround,outround,outround,outround,outround,outround,outround
156,11,"William SmithⒸ , Jim Balatos , John Washburn ,...",DKW B(aking Bread),AUBG A,Djorđa Kratovca 65/8 parking spot,Potsdam A-Z,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Katarina Lazić,Juliette Scheuing,outround,outround,outround,outround,outround,outround,outround,outround
157,12,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",UWODS Revealed Preference for Suffering,GUU (C)an you spot the difference?,DU raam bharose aaye hai,Aberdeen Don&#x27;t ask us about the balkans,Opening Government,Opening Opposition,Closing Government,Closing Opposition,...,Bhavisya sharma,Chloe Stevenson,outround,outround,outround,outround,outround,outround,outround,outround

## Part V. Formatting the data before saving

In [65]:
def get_chair(text):
    return text.split("Ⓒ")[0]

def get_wing1(paneltext):
    parts = paneltext.split(',')
    return parts[1] if len(parts) > 1 else None  # Returns second part if it exists

def get_wing2(paneltext):
    parts = paneltext.split(',')
    if len(parts) > 2:
        value = parts[2]
        return value if 'Ⓣ' not in value else 0
    return 0

def get_trainee1(paneltext):
    parts = paneltext.split(',')
    for part in parts:
        if 'Ⓣ' in part:
            return part
    return 0

def get_trainee2(paneltext):
    parts = [part for part in paneltext.split(',') if 'Ⓣ' in part]
    return parts[1] if len(parts) > 1 else 0

# Define column names
columns = ['Round', 'Panel', 
           'OG', 'OO', 'CG','CO',
           'OG speaker 1', 'OG speaker 2', 'OO speaker 1','OO speaker 2',
           'CG speaker 1', 'CG speaker 2', 'CO speaker 1','CO speaker 2',
           'OG1 score', 'OG2 score', 'OO1 score','OO2 score',
           'CG1 score', 'CG2 score', 'CO1 score','CO2 score',
           'Roundtype', 'Panel_size', 'Voting_panel_size',
           'Chair', 'Wing1', 'Wing2',
           'Trainee1', 'Trainee2', 'Comp_name']

# Get length of df9 
rownumbers = df9.shape[0] 

# Create an empty DataFrame with NaN (or pd.NA) values
data = pd.DataFrame(data={col: [0] * rownumbers for col in columns})

for i in df9.index:
    data.Round[i] = df9.Round[i]
    data.Panel[i] = df9.Panel[i]
    
    lineups = df9.iloc[i,6:10].tolist()
    pos_og = lineups.index('Opening Government')
    pos_oo = lineups.index('Opening Opposition')
    pos_cg = lineups.index('Closing Government')
    pos_co = lineups.index('Closing Opposition')
    teams_order = [pos_og, pos_oo, pos_cg, pos_co]
    
    data.OG[i] = df9.iat[i,teams_order[0]+2]
    data.OO[i] = df9.iat[i,teams_order[1]+2]
    data.CG[i] = df9.iat[i,teams_order[2]+2]
    data.CO[i] = df9.iat[i,teams_order[3]+2]
    
    data.iat[i,6] = df9.iat[i,teams_order[0]+14]
    data.iat[i,7] = df9.iat[i,teams_order[0]+18]
    data.iat[i,8] = df9.iat[i,teams_order[1]+14]
    data.iat[i,9] = df9.iat[i,teams_order[1]+18]
    data.iat[i,10] = df9.iat[i,teams_order[2]+14]
    data.iat[i,11] = df9.iat[i,teams_order[2]+18]
    data.iat[i,12] = df9.iat[i,teams_order[3]+14]
    data.iat[i,13] = df9.iat[i,teams_order[3]+18]
    
    if df9.iat[i,teams_order[0]+22] == 'outround':
        data.iat[i,14] = df9.iat[i,teams_order[0]+10]
        data.iat[i,15] = df9.iat[i,teams_order[0]+10]
        data.iat[i,16] = df9.iat[i,teams_order[1]+10]
        data.iat[i,17] = df9.iat[i,teams_order[1]+10]
        data.iat[i,18] = df9.iat[i,teams_order[2]+10]
        data.iat[i,19] = df9.iat[i,teams_order[2]+10]
        data.iat[i,20] = df9.iat[i,teams_order[3]+10]
        data.iat[i,21] = df9.iat[i,teams_order[3]+10]
        data.Roundtype[i] = "outround"
        
    else:
        data.iat[i,14] = df9.iat[i,teams_order[0]+22]
        data.iat[i,15] = df9.iat[i,teams_order[0]+26]
        data.iat[i,16] = df9.iat[i,teams_order[1]+22]
        data.iat[i,17] = df9.iat[i,teams_order[1]+26]
        data.iat[i,18] = df9.iat[i,teams_order[2]+22]
        data.iat[i,19] = df9.iat[i,teams_order[2]+26]
        data.iat[i,20] = df9.iat[i,teams_order[3]+22]
        data.iat[i,21] = df9.iat[i,teams_order[3]+26]
        data.Roundtype[i] = "inround"
        
    data.Panel_size[i] = df9.Panel[i].count(",")+1
    data.Voting_panel_size[i] = data.Panel_size[i] - df9.Panel[i].count("Ⓣ")
    if df9.Panel[i] != 0:
        data.Chair[i]  = get_chair(df9.Panel[i])
        
    if data.Panel_size[i] > 0:
        data.Wing1[i] = get_wing1(df9.Panel[i])
    if data.Panel_size[i] > 1:
        data.Wing2[i] = get_wing2(df9.Panel[i])
    if data.Panel_size[i] > 0:
        data.Trainee1[i] = get_trainee1(df9.Panel[i])
    if data.Panel_size[i] > 1:
        data.Trainee2[i] = get_trainee2(df9.Panel[i])
        
    data.Comp_name[i] = comp_name
data

C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.OG[i] = df9.iat[i,teams_order[0]+2]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.OO[i] = df9.iat[i,teams_order[1]+2]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.CG[i] = df9.iat[i,teams_order[2]+2]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.CO[i] = df9.iat[i,teams_order[3]+2]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Roundtype[i] = "inround"
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Panel_size[i] = df9.Panel[i].count(",")+1
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Voting_panel_size[i] = data.Panel_size[i] - df9.Panel[i].count("Ⓣ")
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Chair[i]  = get_chair(df9.Panel[i])
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Wing1[i] = get_wing1(df9.Panel[i])
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Trainee1[i] = get_trainee1(df9.Panel[i])
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Comp_name[i] = comp_name
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Round[i] = df9.Round[i]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Panel[i] = df9.Panel[i]
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Wing2[i] = get_wing2(df9.Panel[i])
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Trainee2[i] = get_trainee2(df9.Panel[i])
C:\Users\andra\AppData\Local\Temp\ipykernel_36628\3157058536.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Roundtype[i] = "outround"

,Round,Panel,OG,OO,CG,CO,OG speaker 1,OG speaker 2,OO speaker 1,OO speaker 2,...,CO2 score,Roundtype,Panel_size,Voting_panel_size,Chair,Wing1,Wing2,Trainee1,Trainee2,Comp_name
0,1,Alex MartinⒸ,ANU Guangzhou Mama,A fossil was coaxed out of retirem,HH political overreach into my pants,"Chicago That&#x27;s GBP, the price go up if it...",Dhruv Hariharan,Elanor Parkinson,Linh Đặng-Hoàng,Trimann Johl,...,80,inround,1,1,Alex Martin,NaN,0,0,0,Warwick Pre-EUDC 2025 (29 rms)
1,1,"AmitaiⒸ , Maja Patynowska , Jim BalatosⓉ",DM Hella Adorable,AUBG A,Edinburgh where&#x27;s wurdaan,"E ne le jarabi l&#x27;i la, too much",Helena Hecke,Adora Sabau,Mihaela Peeva,Presian Mihaylov,...,82,inround,3,2,Amitai,Maja Patynowska,0,Jim BalatosⓉ,0,Warwick Pre-EUDC 2025 (29 rms)
2,1,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",Kimbhut Kimakar,KU Mandatory military dropouts,Warwick This House Would Break (But Not Up,Why does Hilary have an Australian,Syeda Tanzeeha Sajida,Nafis Hasan Ruman,Na’ama Benamy,Seungjae Han,...,80,inround,3,2,Dominik Bartosz Jasiolek,Ayushman,0,Surya AnandⓉ,0,Warwick Pre-EUDC 2025 (29 rms)
3,1,"Ellie MiddletonⒸ , Azwad Abdullah AyanⓉ",UCL Rick and Morty Season 2,SPSU SPbU A,GUU (C)an you spot the difference?,This debate? Gnarly,Jack Story,Rick Tan,Vinogradskaia Anastasiia,Ignatenko Roman,...,73,inround,2,1,Ellie Middleton,Azwad Abdullah AyanⓉ,0,Azwad Abdullah AyanⓉ,0,Warwick Pre-EUDC 2025 (29 rms)
4,1,Emma WalkerⒸ,Chen &amp; Qiu,Our Opening is Weak but We Finish S,THUJ HUJI M&amp;S,PUCP Ezeta &amp; Nuñez del Prado,Raymond Qiu,Claire Chen,Moez Uddin Ashrafee,Faisal Raihan,...,75,inround,1,1,Emma Walker,None,0,0,0,Warwick Pre-EUDC 2025 (29 rms)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,9,"ilijaⒸ , Ellie Middleton , Emma Walker , Harve...",LSE When did Aniket get so big and str,quarter life crisis brought us bac,ANU Guangzhou Mama,Cambridge B,Sachin Tissera,Arjun Gunalan,Biser Angelov,Maria Matcheva,...,eliminated,outround,7,7,ilija,Ellie Middleton,Emma Walker,0,0,Warwick Pre-EUDC 2025 (29 rms)
154,10,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",AUBG A,Wiseman and the Tribal Chief,DKW B(aking Bread),IITB Chakraborty &amp; Raghav Raj,Mihaela Peeva,Presian Mihaylov,Henaku Kwasi Owusu,Desmond Dorvlo,...,eliminated,outround,3,3,Henry Clement-Jones,Martin Lim,Ryna Saxena,0,0,Warwick Pre-EUDC 2025 (29 rms)
155,10,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",Potsdam A-Z,Djorđa Kratovca 65/8 parking spot,DKW Vienna (A)mbulance,UP Manila VR,Susanna Wirthgen,Juliette Scheuing,Novak Čelebić,Katarina Lazić,...,eliminated,outround,3,3,Maša Popesković,Aaryav Bansal,Lwandle Ntshangase,0,0,Warwick Pre-EUDC 2025 (29 rms)
156,11,"William SmithⒸ , Jim Balatos , John Washburn ,...",DKW B(aking Bread),AUBG A,Djorđa Kratovca 65/8 parking spot,Potsdam A-Z,Victor Bervoets,Mira Eberdorfer,Mihaela Peeva,Presian Mihaylov,...,eliminated,outround,5,5,William Smith,Jim Balatos,John Washburn,0,0,Warwick Pre-EUDC 2025 (29 rms)
157,12,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",UWODS Revealed Preference for Suffering,GUU (C)an you spot the difference?,DU raam bharose aaye hai,Aberdeen Don&#x27;t ask us about the balkans,Kevin Chen,Jasmeet Randhawa,Harry Braid,Jamie Ghosh,...,eliminated,outround,5,5,Liam Urban,Dominik Bartosz Jasiolek,John Washburn,0,0,Warwick Pre-EUDC 2025 (29 rms)

In [66]:
reordered_columns = ['Comp_name', 'Round', 'Chair', 'Roundtype',
           'OG', 'OO', 'CG','CO',
           'OG speaker 1', 'OG speaker 2', 'OO speaker 1','OO speaker 2',
           'CG speaker 1', 'CG speaker 2', 'CO speaker 1','CO speaker 2',
           'OG1 score', 'OG2 score', 'OO1 score','OO2 score',
           'CG1 score', 'CG2 score', 'CO1 score','CO2 score',
           'Panel_size', 'Voting_panel_size', 'Panel',
           'Wing1', 'Wing2', 'Trainee1', 'Trainee2']
data = data[reordered_columns]
data

,Comp_name,Round,Chair,Roundtype,OG,OO,CG,CO,OG speaker 1,OG speaker 2,...,CG2 score,CO1 score,CO2 score,Panel_size,Voting_panel_size,Panel,Wing1,Wing2,Trainee1,Trainee2
0,Warwick Pre-EUDC 2025 (29 rms),1,Alex Martin,inround,ANU Guangzhou Mama,A fossil was coaxed out of retirem,HH political overreach into my pants,"Chicago That&#x27;s GBP, the price go up if it...",Dhruv Hariharan,Elanor Parkinson,...,76,79,80,1,1,Alex MartinⒸ,NaN,0,0,0
1,Warwick Pre-EUDC 2025 (29 rms),1,Amitai,inround,DM Hella Adorable,AUBG A,Edinburgh where&#x27;s wurdaan,"E ne le jarabi l&#x27;i la, too much",Helena Hecke,Adora Sabau,...,—,80,82,3,2,"AmitaiⒸ , Maja Patynowska , Jim BalatosⓉ",Maja Patynowska,0,Jim BalatosⓉ,0
2,Warwick Pre-EUDC 2025 (29 rms),1,Dominik Bartosz Jasiolek,inround,Kimbhut Kimakar,KU Mandatory military dropouts,Warwick This House Would Break (But Not Up,Why does Hilary have an Australian,Syeda Tanzeeha Sajida,Nafis Hasan Ruman,...,77,81,80,3,2,"Dominik Bartosz JasiolekⒸ , Ayushman , Surya A...",Ayushman,0,Surya AnandⓉ,0
3,Warwick Pre-EUDC 2025 (29 rms),1,Ellie Middleton,inround,UCL Rick and Morty Season 2,SPSU SPbU A,GUU (C)an you spot the difference?,This debate? Gnarly,Jack Story,Rick Tan,...,74,73,73,2,1,"Ellie MiddletonⒸ , Azwad Abdullah AyanⓉ",Azwad Abdullah AyanⓉ,0,Azwad Abdullah AyanⓉ,0
4,Warwick Pre-EUDC 2025 (29 rms),1,Emma Walker,inround,Chen &amp; Qiu,Our Opening is Weak but We Finish S,THUJ HUJI M&amp;S,PUCP Ezeta &amp; Nuñez del Prado,Raymond Qiu,Claire Chen,...,74,76,75,1,1,Emma WalkerⒸ,None,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Warwick Pre-EUDC 2025 (29 rms),9,ilija,outround,LSE When did Aniket get so big and str,quarter life crisis brought us bac,ANU Guangzhou Mama,Cambridge B,Sachin Tissera,Arjun Gunalan,...,eliminated,eliminated,eliminated,7,7,"ilijaⒸ , Ellie Middleton , Emma Walker , Harve...",Ellie Middleton,Emma Walker,0,0
154,Warwick Pre-EUDC 2025 (29 rms),10,Henry Clement-Jones,outround,AUBG A,Wiseman and the Tribal Chief,DKW B(aking Bread),IITB Chakraborty &amp; Raghav Raj,Mihaela Peeva,Presian Mihaylov,...,advancing,eliminated,eliminated,3,3,"Henry Clement-JonesⒸ , Martin Lim , Ryna Saxena",Martin Lim,Ryna Saxena,0,0
155,Warwick Pre-EUDC 2025 (29 rms),10,Maša Popesković,outround,Potsdam A-Z,Djorđa Kratovca 65/8 parking spot,DKW Vienna (A)mbulance,UP Manila VR,Susanna Wirthgen,Juliette Scheuing,...,eliminated,eliminated,eliminated,3,3,"Maša PopeskovićⒸ , Aaryav Bansal , Lwandle Nts...",Aaryav Bansal,Lwandle Ntshangase,0,0
156,Warwick Pre-EUDC 2025 (29 rms),11,William Smith,outround,DKW B(aking Bread),AUBG A,Djorđa Kratovca 65/8 parking spot,Potsdam A-Z,Victor Bervoets,Mira Eberdorfer,...,eliminated,eliminated,eliminated,5,5,"William SmithⒸ , Jim Balatos , John Washburn ,...",Jim Balatos,John Washburn,0,0
157,Warwick Pre-EUDC 2025 (29 rms),12,Liam Urban,outround,UWODS Revealed Preference for Suffering,GUU (C)an you spot the difference?,DU raam bharose aaye hai,Aberdeen Don&#x27;t ask us about the balkans,Kevin Chen,Jasmeet Randhawa,...,eliminated,eliminated,eliminated,5,5,"Liam UrbanⒸ , Dominik Bartosz Jasiolek , John ...",Dominik Bartosz Jasiolek,John Washburn,0,0

In [67]:
teamtab.to_excel(comp_name+'_teamtab_done'+'.xlsx', index=True)
speakertab.to_excel(comp_name+'_speakertab_done'+'.xlsx', index=True)
data.to_excel(comp_name+'_rounds_done'+'.xlsx', index=True)